export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  forgetPassword: '/forget-password',
  verification: '/verification',
  updatePassword: '/update-password',
  contact: '/contact',
  about: '/about',
  services: '/services',
  cart: '/cart',
  checkout: '/cart/checkout',
  product: '/products/polysave-hd-water-tanksappartments',
  singleProduct: '/products/polysave-hd-water-tanksappartments/1',
  orderHistory: '/dashboard/order-history',
  wishlist: '/dashboard/wishlist',
  myAddress: '/dashboard/address',
  profileSetting: '/dashboard/profile',
  password: '/dashboard/password',
}
