export const routes = {
  login: '/',
  dashboard: '/dashboard',
  forgetPassword: '/forget-password',
  verification: '/verification',
  updatePassword: '/update-password',
  // userManagement :"/user-management",
  paymentMonitoring: '/payment-monitoring',
  transactionsMonitoring: '/transactions',
  reportsAndAnalytics: '/reports-and-analytics',
  disputes: '/disputes',
  platformConfiguration: '/platform-configuration',
  platformUsers: '/platform-users',
  supportAndQueries: '/support-and-queries',
  jobsOversight: '/jobs-oversight',
  feesConfiguration: '/platform-configuration/fees-configuration',
  coupons: '/platform-configuration/coupons',
  userManagementCorporate: '/user-management/corporate',
  userManagementRecruiter: '/user-management/recruiter',
}
