export const routes = {
  login: '/',
  register: '',
  dashboard: '/dashboard',
  forgetPassword: '/forget-password',
  verification: '/verification',
  updatePassword: '/update-password',
  contact: '/contact',
  about: '/about',
  services: '/services',
  cart: '/cart',
  checkout: '/cart/checkout',
  singleProduct: '/properties/categories/[productName]',
  orderHistory: '/dashboard/order-history',
  wishlist: '/dashboard/wishlist',
  myAddress: '/dashboard/address',
  profileSetting: '/dashboard/profile',
  password: '/dashboard/password',
}
